// <auto-generated />
using System;
using FuturoDoTrabalho.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuturoDoTrabalho.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119221059_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Competencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competencias");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Fundamentos de IA e Machine Learning",
                            Nome = "Inteligência Artificial"
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Data Analytics e tomada de decisão baseada em dados",
                            Nome = "Análise de Dados"
                        },
                        new
                        {
                            Id = 3L,
                            Descricao = "Empatia, colaboração e comunicação",
                            Nome = "Soft Skills"
                        });
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Matricula", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Trilha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FocoPrincipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trilhas");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CargaHoraria = 40,
                            Descricao = "Introdução à IA aplicada ao contexto corporativo",
                            FocoPrincipal = "IA",
                            Nivel = "INICIANTE",
                            Nome = "Trilha de IA para Negócios"
                        },
                        new
                        {
                            Id = 2L,
                            CargaHoraria = 60,
                            Descricao = "Analytics, métricas e storytelling de dados",
                            FocoPrincipal = "Dados",
                            Nivel = "INTERMEDIARIO",
                            Nome = "Trilha de Dados para Tomada de Decisão"
                        });
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.TrilhaCompetencia", b =>
                {
                    b.Property<long>("TrilhaId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompetenciaId")
                        .HasColumnType("bigint");

                    b.HasKey("TrilhaId", "CompetenciaId");

                    b.HasIndex("CompetenciaId");

                    b.ToTable("TrilhasCompetencias");

                    b.HasData(
                        new
                        {
                            TrilhaId = 1L,
                            CompetenciaId = 1L
                        },
                        new
                        {
                            TrilhaId = 1L,
                            CompetenciaId = 3L
                        },
                        new
                        {
                            TrilhaId = 2L,
                            CompetenciaId = 2L
                        },
                        new
                        {
                            TrilhaId = 2L,
                            CompetenciaId = 3L
                        });
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaAtuacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelCarreira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("FuturoDoTrabalho.Api.Domain.Entities.Trilha", "Trilha")
                        .WithMany("Matriculas")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuturoDoTrabalho.Api.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Matriculas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.TrilhaCompetencia", b =>
                {
                    b.HasOne("FuturoDoTrabalho.Api.Domain.Entities.Competencia", "Competencia")
                        .WithMany("TrilhaCompetencias")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuturoDoTrabalho.Api.Domain.Entities.Trilha", "Trilha")
                        .WithMany("TrilhaCompetencias")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competencia");

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Competencia", b =>
                {
                    b.Navigation("TrilhaCompetencias");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("Matriculas");

                    b.Navigation("TrilhaCompetencias");
                });

            modelBuilder.Entity("FuturoDoTrabalho.Api.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
